### ISSUE TITLE
[0.5pt] Find external API - group task

### ISSUE THREAD

**Issue by fabgrel10** [fabgrel10/js-capstone#20]
Find an API to base the development of the webapp around it. The API should allow you to
  - Get a list of items with a unique item id (or generate the unique id).
  - For a given item, get detailed information about it.
choose an APIs that doesn't need authentication. if you select an API that requires authentication, you should implement it on your own. Also, if you select an API that provides image resources your webapp will be more visual.

**Comment by fabgrel10** [comment]
We decided to use the following APIs:

- [Robohash](https://robohash.org/) to retrieve pictures
- [JSONPlaceholder](https://jsonplaceholder.typicode.com/) which supports a list of items with a unique item id  and detailed information.

None of the APIs require authentication as both are public.

**Comment by John-Arboleda** [comment]
Neither of those API needs authentication
