### ISSUE TITLE
JavaScript group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by fabgrel10** [fabgrel10/js-capstone#21]
### This is the first issue created for first review of the JavaScript group capstone.

**Link to the GH repo**: [https://github.com/fabgrel10/js-capstone](https://github.com/fabgrel10/js-capstone)
**Team members**: John Arboleda, Fabricio Garcia.

**What has been accomplished?**

- [x] Create an empty repository for your group project
- [x] Follow the steps described in curriculum-tools-copy-projects
- [x] Open the GitHub project (Kanban board) in your team repo
- [x] Decide who in your team is the Student A, and Student B
- [x] Assign students themselves to the correct cards

**Comment by arslanbisharat** [comment]
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_
